[package]
name = "gamelog"
version = "0.1.0"
authors = ["Ben Bariteau <firba1@gmail.com>"]

[dependencies]
iron = "0.5.*"
router = "0.5.*"
urlencoded = "^0.5.0"
rusqlite = "^0.10.1"
error-chain = "^0.7.1"
